# Generated by Django 2.1.5 on 2019-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetsParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('world_type', models.IntegerField(choices=[(1, 'Planets of Kerbal world'), (2, 'Planets of real(RSS) world')])),
                ('type_of_object', models.IntegerField(choices=[(1, 'Planet'), (2, 'Satellite')])),
                ('radius', models.IntegerField()),
                ('atmosphere_attitude', models.IntegerField()),
                ('mass', models.BigIntegerField()),
                ('standard_gravitational_parameter', models.BigIntegerField()),
                ('day_time', models.IntegerField()),
            ],
        ),
    ]
