# Generated by Django 2.1.5 on 2019-02-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetsparameters',
            name='day_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='planetsparameters',
            name='mass',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='planetsparameters',
            name='radius',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='planetsparameters',
            name='standard_gravitational_parameter',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='planetsparameters',
            name='type_of_object',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Planet'), (2, 'Satellite')]),
        ),
        migrations.AlterField(
            model_name='planetsparameters',
            name='world_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Planets of Kerbal world'), (2, 'Planets of real(RSS) world')]),
        ),
    ]
